### ISSUE TITLE
Is using slingshot's throw+ for exceptions a good idea?

### ISSUE THREAD

**Issue by siyopao** [mpenet/alia#100]
Hi! I am working on some code where I want to do different things depending on what type of `com.datastax.driver.core.exceptions` is thrown by `alia/execute` and am finding it a bit confusing to extract that information from an `ExceptionInfo`. Is there an ideal way?

Anyway, I was thinking that maybe it would be nice if the exceptions were thrown by `throw+` and then `catch` could filter based on `:cause` or `:throwable` or whatever it is that would work. Is this a good idea? I would be willing to attempt a PR if you think so.

Best wishes!

**Comment by mpenet** [comment]
We use https://github.com/mpenet/ex. 
But this is fairly open as is, you should be able to plug use slingshot or something else easily.

**Comment by siyopao** [comment]
Ah, I didn't notice that! That's embarrassing. Thank you, I will check it out.
