### ISSUE TITLE
`INSERT` a blob

### ISSUE THREAD

**Issue by harold** [mpenet/alia#114]
Hi! Thanks for alia - we are needing to interact with Cassandra in non-trivial ways from Clojure for the first time, and this library looks like it may be a big leg up.

So far I have successfully connected to the cluster, and queried out some data with no trouble. Quite fun, actually!

I would like to do some updates to the data now, and the column of interest is a `blob`.

I ended up doing something like this:

```clojure
(defn- update-byte-array!
  [session pk byte-array]
  (let [statement (alia/prepare session "INSERT into t (pk, ba) VALUES (?, ?);")]
    (alia/execute session statement {:values [pk byte-array]})))
```

Question: Is this good? 

I couldn't find any precedent online (though maybe I was searching for the wrong terms, I am a neophyte in this area).

---

If this is good, let me know and if you'd like I can do a PR to update the tests and guide in this repo to suggest this as a technique.

If this is not good, what is the best way to make these kinds of updates?

Thanks again for this lib, you time, and your consideration.

**Comment by mpenet** [comment]
Hi Harold,

> Hi! Thanks for alia - we are needing to interact with Cassandra in non-trivial ways from Clojure for the first time, and this library looks like it may be a big leg up.

You're welcome. 

> Question: Is this good?

Yes that's fine. Feel free to send a pr for doc/tests, that'd be very much welcomed.
