### ISSUE TITLE
Custom decoders

### ISSUE THREAD

**Issue by d-t-w** [mpenet/alia#26]
Within the codec ns there are a number of decoders, but I can't see any way of declaring a custom one?

I would like to be able to specify decoders, similar to the existing PCodec support for Joda but decode rather than encode, i.e.:

DataType$Name/TIMESTAMP (timec/to-date-time (.getDate x idx))

I'm happy to supply a PR, but I wasn't quite sure where/if to start.

**Comment by mpenet** [comment]
in theory this is not "open" at the moment as it depends on values not types for the dispatch, I ll see if we can make this a protocol instead (feel free to try yourself too). 
I'd gladly take a pr for this

**Comment by d-t-w** [comment]
Cool, I'll have a play and see what I come up with. Might be a little slow I've got a bit on but I'll get there!

**Comment by mpenet** [comment]
in theory this could be a multimethod, it would be open, but we'd pay that losing a bit of performance compared to the hashmap we have now. I'd only trade this for a protocol if thats feasible.

**Comment by d-t-w** [comment]
sure sounds reasonable.

**Comment by mpenet** [comment]
I might have something already :] I ll let you know

**Comment by mpenet** [comment]
Ok it's in master and clojars.

**Comment by mpenet** [comment]
I started by basically rewriting the decoding around getbyteunsafe etc, but we gain nothing by doing that, it actually breaks the nested collection types decoding and to get back to it I was actually penalized in perfs. So I just wrapped the decoding in a new protocol function, which seems to be inlined, I can't see a difference in perf now, it works with nested collection/UDTs and the code is nearly identical.

**Comment by mpenet** [comment]
that said, wait a bit, travis is complaining... I might have broken something

**Comment by mpenet** [comment]
and we're back in business: fixed in [cc.qbits/alia "2.3.7"]

**Comment by d-t-w** [comment]
thanks Max, the impl is very straight forward.

I've added a decoder to the joda-time ns in the pull request above.

The only thing I would question is whether it is necessary to add 'decode' to the PCodec protocol (though the name 'codec' does imply bi-directional behaviour). Using the protocol to dispatch means you'll likely never have an encode/decode pair for the same type (that went over my head until I added the decode fn on joda.DateTime first, before realising it needed to go on util.Date). You could just have encode and use that anywhere you want to encode from one type to another, or leave encode/decode and use that to be clear that some behaviour is applied to data going into C* and some coming out.

ta.
Derek

**Comment by mpenet** [comment]
Thanks for the PR. 

Yeah I thought about it as well, while it's true it's probably a bit overkill, it makes things clearer imho. 
I might add an optional nippy codec as well.
