### ISSUE TITLE
Async execution and exceptions

### ISSUE THREAD

**Issue by d-t-w** [mpenet/alia#32]
The docstring of execute-chan includes: "Exceptions are sent to the channel as a value" which seems like a very reasonable approach. However it's also possible to call this function in a manner which will cause an exception to be thrown, and no channel returned, i.e.

``` 
(execute-chan prepared-statement {:values [:fails-to "bind"]}})
```

This is due to (query->statement query values) being executed synchronously and outside the scope of a try/catch. There may be other examples, I primarily use execute-chan and execute-chan-buffered.

Happy to create a PR if this is something worth picking up.

**Comment by mpenet** [comment]
That makes perfect sense yes, a PR is welcomed. I will add you to committers as well given how many patches you're providing. 

Thanks

**Comment by mpenet** [comment]
I gave it a (quick)shot this morning here: https://github.com/mpenet/alia/tree/feature/better-async-ex 
If you can have a look and tell me if that's what you had in mind.

**Comment by d-t-w** [comment]
Cool I'll take a look shortly.

**Comment by d-t-w** [comment]
Hey Max, yeah that looks like what I was thinking, though I would have probably just thrown raw exceptions out of set-statement-options and query->statement, I prefer your approach of converting to ex-info earlier.

Does the manifold impl need a similar approach or are thrown exceptions handled there? I'm happy to look at it if you're busy.

**Comment by mpenet** [comment]
Yep it does, I forgot about them, feel look at it

**Comment by d-t-w** [comment]
I worked through the other execution impls in this PR: https://github.com/mpenet/alia/pull/33

I'm not a git pro, so I wasn't sure whether I should have raised that PR on the feature branch or not, seemed sensible but just let me know.

I'm looking at adding some tests now, and I think there's the possibility of one further raw exception being thrown in each case of:

```
(.executeAsync session statement)
```

Would you rather if raw exceptions were not returned if at all avoidable and always convert to ex-info?

also, how do you feel about:

```
(let [^Statement statement (query->statement query values)]
         (set-statement-options! statement routing-key retry-policy
                                 tracing? idempotent?
                                 consistency serial-consistency fetch-size
                                 timestamp paging-state)
         (let [^ResultSetFuture rs-future (.executeAsync session statement)]
           (Futures/addCallback
```

as opposed to

```
 (let [^Statement statement (-> (query->statement query values)
                                (set-statement-options! routing-key retry-policy
                                                        tracing? idempotent?
                                                        consistency serial-consistency fetch-size
                                                        timestamp paging-state))
       ^ResultSetFuture rs-future (.executeAsync session statement)]
         (Futures/addCallback
```

**Comment by mpenet** [comment]
I prefer the former as set-statement-options! is unpure and doesn't return anything meaningfull. 

About execute-async we could simply create a thin fn wrapper to it that throws an ex-info, or not, I am starting to have mixed feelings about wrapping everything in ex-info. 
While in theory it could be more convenient to clj users (ex via catch-data), it's also a level of indirection, originally where/when I did this it was to cover something missing in the driver (informative error output with values + query), but here it buy us close to nothing. wdyt?

**Comment by d-t-w** [comment]
I'm in two minds myself, on the one hand I think the ex-info data gives a
fuller picture from a library / general case, but on the other hand I don't
use it in any of my application workflow. I look for any exception returned
on the channel and then I raise an error event with some current
application state and send that to riemann for metrics/reporting.

**Comment by mpenet** [comment]
Yep same here. I took the decision to throw both kinds, also some people might rely on these in their code so I don't want to change it for now. I made a few cosmetic change here and there, but I think it's mostly ready to be merged in master. Feel free to have a look, I ll let it rest for a day or two.

**Comment by d-t-w** [comment]
Sounds like a good idea to me. I've got something else bubbling away I'll push a feature branch shortly and you can let me know what you think.

**Comment by coltnz** [comment]
Nice thing about ex-info is as a way to adorn with user validation messages / system codes on the way through.

**Comment by mpenet** [comment]
Yup, I can't deny it, I like ex-info a lot more as well, but I am not sure about wrapping every single exception from the driver in them, and breaking backward compat for some. At least not now.
