### ISSUE TITLE
Consider using shaded java driver.

### ISSUE THREAD

**Issue by d-t-w** [mpenet/alia#34]
Datastax provide a version of the driver where the netty dependency is shaded:

https://datastax.github.io/java-driver/2.1.6/features/shaded_jar/

I have a conflict between the version of Netty my network service framework is based on (4.0.29) and the version in the driver currently (4.0.27).

I think it's possible for me to work around this in my project with exclusions and not altering Alia (I haven't actually tried that yet), if you're so inclined it might not be a bad idea to use the shaded version.

**Comment by mpenet** [comment]
sounds good
