### ISSUE TITLE
Support named bindings of values to PreparedStatements

### ISSUE THREAD

**Issue by d-t-w** [mpenet/alia#38]
CQL and the Datastax driver support named bindings in CQL, i.e.:

```
"INSERT INTO table (id, location, contact) values (:id, :address, :phone)";
```
as opposed to positional:
```
"INSERT INTO table (id, location, contact) values (?, ?, ?)"
```

This is useful, because when using PreparedStatement (and assuming our data-structures are generally maps), we have to also maintain a mapping from each map to the PreparedStatement value positional order, which is cumbersome.

If we allow alia to accept a map of values, we can bind that to the named parameters in the CQL, and execute similarly to:

```
(alia/execute session statement {:values {:id 1 :address "some-address" :phone "123-321"}})
```

**Comment by d-t-w** [comment]
As an aside, it seems the named bindings default to the column name, so you can:

```
"INSERT INTO table (id, location, contact) values (?, ?, ?)"
```
and
```
(execute session statement {:id 1 :location "some-address" :contact "123-321"})
```
Because the map keys and columns are aligned it will insert. You could also insert into that prepared query via:
```
(execute session statement [1 "some-address" "123-321"])
```

I'm not sure this behaviour is intentional, and the only other thing to add is you cannot mix both positional and named bindings. Well, the CQL will compile, and the driver will prepare it, but it resets the positional bindings when you try and set a named one.

**Comment by mpenet** [comment]
I think you're missing :value ... in your examples but I got it I think. 

Very cool stuff, one small nitpick, could you move the protocol and its extend to codec?

**Comment by d-t-w** [comment]
Yes, will make those changes now.

**Comment by d-t-w** [comment]
Moved.

**Comment by mpenet** [comment]
applied/merged
