### ISSUE TITLE
Null UTD columns cause NPE

### ISSUE THREAD

**Issue by qzg** [mpenet/alia#40]
I have a table with a UDT column.  Rows which have a value for the UDT column work normally but rows which have no value for the UDT column cause a NullPointerException.  Also, "SELECT * FROM tablename" where "table name" is a table that has some null cells for the UDT column causes an NPE which refers to codec.clj:90.

**Comment by mpenet** [comment]
Thanks for the report, I'll cut a release shortly (in minutes) with the fix. It will likely be 2.6.2
