### ISSUE TITLE
Should UDT types and value names be converted to keywords ?

### ISSUE THREAD

**Issue by pyr** [mpenet/alia#42]
Hi!

`qbits.alia.codec` decodes UDTs as maps with string keys. It seems as though the UDT API only allows strings for names and value names. Would you be open to switching it to keywords ? If so I can cook a PR.

Cheers,
pyr

**Comment by mpenet** [comment]
Sure that makes sense, I was thinking about possible future improvements of UDTs where arbitrary key could be supported, but I doubt this will ever happen, PR welcomed!

**Comment by pyr** [comment]
For reference, this is what I'm trying to avoid: https://github.com/pyr/cyanite/blob/feature/updated-core/src/io/cyanite/store/pure.clj#L25-L29

I'll work on a PR this week, thanks!

**Comment by mpenet** [comment]
Alright, let me know if you're short in time I can do it now, it'd take minutes.  
I am also thinking about easing the encoding to udt values for prepared statements at some point and avoid this kind of things: https://github.com/pyr/cyanite/blob/feature/updated-core/src/io/cyanite/store/cassandra.clj#L45-L61

**Comment by pyr** [comment]
What would be your approach ? (I'd love that) the thing is that you need the type context. I was wondering if a map with metadata wouldn't do the trick

```clojure
 ^{::alia/udt-type :metric_resolution} {:precision 5 :period 3600}
```

**Comment by mpenet** [comment]
I am not sure yet, just started thinking about that. What you suggest could could work, or allowing to declare 1 udt-encoder per type and have it's instance used as a fn: 

```clj 
(def udt-user (udt-encoder session keyspace {:type "user_type"}))
```

then 

```clj
(udt-user {:name ..., :foo ...})
```

This would save some calls to session.metadata.getUserType or allow us not to keep some state (avoid internally memoizing the getUserType return value we got from the var metadata, etc). 



Not sure yet, I am all ears if you have suggestions.

**Comment by mpenet** [comment]
Internally we just use a protocol for the encoding to the right method calls, just like we did recently for named parameters, no need to get fancy I think (like using the udtmappingmanager or whatnot). This would also work with nested udts

**Comment by mpenet** [comment]
I implemented an example of what in mind in https://github.com/mpenet/alia/commit/642752ecde84aef30da425f9aff373512e1f41cc 

It's quite straightforward.

**Comment by mpenet** [comment]
I also did the same for tuples as they cannot just be fed from clojure collection types in UDTs or if nested in other tuples for some reason (internal java-driver thing, I guess the fact that a collection is accepted as prepared statement value for a tuple is just "luck" at the moment, they probably just encode the same way at a protocol level).  In any case it's safer that way.  I will let it rest for a couple of hours/days and then merge if nothing comes up. 

Cheers
