### ISSUE TITLE
query result return com.datastax.driver.core.UDTValue object instead of a map

### ISSUE THREAD

**Issue by taoliveops** [mpenet/alia#45]
I have a UDT like this:
```clojure
(create-type :list_field
                                    (if-not-exists)
                                    (column-definitions {:type :text
                                                             :name :text
                                                             :label :text
                                                             :required :boolean}))
```
I can insert the UDT value without problem by https://github.com/mpenet/alia/blob/master/docs/guide.md#udt-and-tuple

But when I query the data and the result looks like this:
```clojure
 #object[com.datastax.driver.core.UDTValue 0x2d506d0c
 "{type:'integer', name:'reason-code', label:null, required:true}"]
```

It seems alia return the UDTValue java object instead of a map. If I use [bean](https://clojuredocs.org/clojure.core/bean), I get follow result
```clojure
{:class com.datastax.driver.core.UDTValue, 
:type #object[com.datastax.driver.core.UserType 0x139f5bf4 "frozen<mykeyspace.list_field>"]}
```

Could this be a bug in alia or by design?

**Comment by mpenet** [comment]
It's an optimisation, but maybe I could change this behavior. 
A udt at the top level will be deserialized natively (same for nested udts), a udt in a collection type will not (just to prevent double walking the collection since I defer to the driver for this deserialisation. I guess I could do it myself and prevent this weird case. 

Alternatively you can just extend the protocol that wraps decoding of values at runtime https://github.com/mpenet/alia/blob/master/src/qbits/alia/codec.clj#L105-L129 to perform whatever custom decoding you need in Set/Map/List types.

Thanks for the raising this to my attention.

**Comment by taoliveops** [comment]
Thanks for the suggestion, Max. 

It seems it need [com.datastax.driver.mapping.MappingManager](http://docs.datastax.com/en/drivers/java/2.1/com/datastax/driver/mapping/MappingManager.html) to handle the UDTValue instead of [bean](https://clojuredocs.org/clojure.core/bean).

Do you think this the right way to do it?

**Comment by mpenet** [comment]
I don't think so, imho it's easier to use only the UDTValue instance, same way I did it here: 
https://github.com/mpenet/alia/blob/master/src/qbits/alia/codec.clj#L89-L103

I am thinking about supporting auto decoding in deeply nested collections, maybe something optional not to impose walking collections when not needed or going low level and doing this from the ByteBuffer instance directly. Doing it naively (walking/iterating colls) is fairly easy, doing it in an efficient and performant way will require some thinking.

**Comment by mpenet** [comment]
This is now automatic in master, I will let it rest for a day or two and release.

**Comment by taoliveops** [comment]
That's great news. Thanks, Max! Looking forward the new release.

**Comment by mpenet** [comment]
It's on clojars as 2.9.0. Be sure to read the [changelog](https://github.com/mpenet/alia/blob/master/CHANGELOG.md).
