### ISSUE TITLE
Submitting changes to 2.12.x

### ISSUE THREAD

**Issue by pyr** [mpenet/alia#50]
Hi!

I'm trying to address a small dependency issue on 2.12.1 but I am failing to find a tag or branch to base my work on, is there something that I missed?

**Comment by mpenet** [comment]
Hi, 
There's no branch for it (nor tag, my bad). I am curious what's the dependency issue?

**Comment by pyr** [comment]
alia is incompatible with clojure.tools.namespace since
clojure.core.async 0.2.371 wants clojure.tools.reader 0.9.x and
tools.namespace 1.0.x, moving to core.async 0.2.374 mitigates this, I
would also move to core.memoize 0.5.8 to avoid further dependency clashes.

**Comment by mpenet** [comment]
I see. 

If you're running c* 2.2+ you could consider moving to alia 3.x version, memoize is no longer a dependency and all the rest in optional on 3.x. 

2.12.1 is 761ed9b7aa488575fed01a85aa989cc17657adba 
I ll add the missing tags when I have some time later today, sorry about that. 

But this sounds like you could deal with the issue with leiningen exclude + explicit deps in the meantime, even tho it's not ideal.

**Comment by mpenet** [comment]
In any case, I ll add you to contributors, if you prefer to add a branch with support for c* 2.2- I ll gladly take it and release on clojars

**Comment by pyr** [comment]
Overriding the deps explicity is the way I'm mitigating it now, indeed.
Can I suggest a branch for 2.12.x for this type of small maintenance
changes?

We're moving to C* 2.2.x but not quite there :-)

**Comment by pyr** [comment]
Thanks! I'll start a branch for the commit later today, cheers!

**Comment by mpenet** [comment]
actually they made 3.x fully backward compatible : 

"The Java client driver 3.0 (branch 3.0) is compatible with Apache Cassandra 1.2, 2.0, 2.1, 2.2 and 3.0 (see this page for the most up-to-date compatibility information)."
https://datastax.github.io/java-driver/#compatibility

**Comment by pyr** [comment]
Ah!

This changes everything, I might not bother then, I much prefer the module structure in latest alia

**Comment by pyr** [comment]
(feel free to remove if you change your mind on the contributor status)

**Comment by mpenet** [comment]
I will leave the contributor thing. there's no harm to it. 

cheers!
