### ISSUE TITLE
execute on prepared statement fails with timestamp binding

### ISSUE THREAD

**Issue by chrisalbright** [mpenet/alia#59]
I'm trying to execute a prepared statement to insert a `timestamp` value using named parameters. I'm getting the following error:

`clojure.lang.ExceptionInfo: Query binding failed {:type :qbits.alia/bind-error, :exception #error {
 :cause "java.util.Date cannot be cast to com.datastax.driver.core.LocalDate"
 :via
 [{:type java.lang.ClassCastException
   :message "java.util.Date cannot be cast to com.datastax.driver.core.LocalDate"
   :at [qbits.alia.codec$eval4743$fn__4744 invoke "codec.clj" 153]}]`

I think I've tracked it down to `qbits.alia.codec.clj` in the `java.util.Date` implementation of the `PNamedBinding` protocol. It is currently calling `setDate` with a `java.util.Date` argument, but in the Java driver, `setDate` un-intuitively takes a `com.datastax.driver.core.LocalDate` while `setTimestamp` takes a `java.util.Date`

Anyway, it seems like an easy fix. Pull request coming soon.

**Comment by mpenet** [comment]
This apparently changed between 2.0 and 3.0 drivers version: 

https://docs.datastax.com/en/drivers/java/3.0/com/datastax/driver/core/SettableByNameData.html#setDate-java.lang.String-com.datastax.driver.core.LocalDate-

https://docs.datastax.com/en/drivers/java/2.1/com/datastax/driver/core/SettableByNameData.html#setDate-java.lang.String-java.util.Date-
