### ISSUE TITLE
Cluster query-options configuration ignored

### ISSUE THREAD

**Issue by d-t-w** [mpenet/alia#62]
Currently alia/cluster ignores any query-options that are passed, this is due to a bug in the cluster-options integration with the ClusterBuilder (retrieving and setting on the configured QueryOptions, which is then discarded, rather than using .withOptions).

This means that all queries that rely on the query options provided at cluster configuration time will be executing with the datastax defaults of LOCAL_ONE consistency, SERIAL serial_consistency, and 5000 as the fetch size regardless of configuration provided. 

I've a PR which fixes the query-options case, but I suspect it's also likely the pooling-options, netty-options, etc are similarly affected.

**Comment by d-t-w** [comment]
At a glance this will also likely occur with socket-options and pooling-options.

**Comment by mpenet** [comment]
This should be fixed, thanks again.
