### ISSUE TITLE
Alia-all 3.1.11 is not deployed on clojars

### ISSUE THREAD

**Issue by rhacker** [mpenet/alia#65]
Just to let you know that `alia-all 3.1.11` is not deployed yet, only `alia-all 3.1.10` is deployed.

**Comment by mpenet** [comment]
Hi,

There is no alia 3.1.11. There is alia-all 3.1.11 tho. 
The project is split in many modules each on their own version, see the module directory.

**Comment by rhacker** [comment]
@mpenet I'm sorry I meant `alia-all 3.1.11`. 
https://clojars.org/cc.qbits/alia-all/versions

**Comment by mpenet** [comment]
Right! i ll look into this when i am home

**Comment by mpenet** [comment]
Here you go. Thanks for the head's up

**Comment by rhacker** [comment]
Great !
