### ISSUE TITLE
NoClassDefFoundError while using alia

### ISSUE THREAD

**Issue by devasiajoseph** [mpenet/alia#76]
When trying to use the following code

`(require '[qbits.alia :as alia])`

I am getting the error:

```
java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
clojure.lang.Compiler$CompilerException: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback, compiling:(qbits/alia/udt.clj:109:12)
```

Here is my dependency tree. I am using this in a luminus web template

[https://gist.github.com/devasiajoseph/ba8beafafdda8ee1350de01c799e4fc8](https://gist.github.com/devasiajoseph/ba8beafafdda8ee1350de01c799e4fc8
)

What did I miss?

**Comment by devasiajoseph** [comment]
Seems like the issue is related to Clojurescript conflict #74

**Comment by mpenet** [comment]
It might be possible to get around this with an exclude on google closure to downgrade guava to 16.x, I didnt get time to try yet tho
