### ISSUE TITLE
Non descriptive NullPointerException when accidentally inserting data of wrong type

### ISSUE THREAD

**Issue by ifesdjeen** [mpenet/alia#77]
When using an async `execute` function, if you accidentally pass argument of a wrong type, you will get an exception that's a bit hard to understand:

```
Caused by: java.lang.NullPointerException
        at qbits.alia$execute_async.invokeStatic(alia.clj:415)
        at qbits.alia$execute_async.invoke(alia.clj:380)
```

I'll debug / handle it later, just leaving info here not to forget..

**Comment by mpenet** [comment]
Odd, seems that this path should be covered. Let me know what you find.

**Comment by mpenet** [comment]
Closing, as this is now covered by the specs we provider (if you use them at dev time)
