### ISSUE TITLE
 java.lang.NoSuchFieldException: builder

### ISSUE THREAD

**Issue by lxsameer** [mpenet/alia#82]
Hi
When I try to require `alia` in the repl I get this exception:
```
 java.lang.NoSuchFieldException: builder
```
Or when I try to execute the following code I get the same exception:
```clojure
(defn connect
  []
  (let [host    (env :cassandra-host)
        cluster (alia/cluster {:contact-points [host]
                               :load-balancing-policy :default})]
    (alia/connect cluster)))
```

**Comment by mpenet** [comment]
Thanka for the report, I ll have a look on monday first thing.

**Comment by mpenet** [comment]
I can't reproduce, on what version are you?

**Comment by mpenet** [comment]
It's worth noting that the edn style syntax for policies options is only available from 4.0.0-beta9+

**Comment by lxsameer** [comment]
I'm using `4.0.0-beta10`

**Comment by mpenet** [comment]
Can you provide a simple project.clj + file that would allow me to reproduce the issue?

**Comment by lxsameer** [comment]
hmmm it would take some time. I'll do my best

**Comment by lxsameer** [comment]
Also this is the file I'm using to generate this problem:
```clojure
(ns psychopomps.tasks.db
  (:require [qbits.alia   :as alia]
            [environ.core :refer [env]]
            [qbits.hayt   :refer [create-keyspace with]]))

(defn connect
  []
  (let [host    (env :cassandra-host)
        cluster (alia/cluster {:contact-points [host]
                               :load-balancing-policy :default})]
    (alia/connect cluster)))

(defn setup-db
  [session]
  (let [keyspace-name (env :cassandra-keyspace-name)]
    (alia/execute session
                  (create-keyspace keyspace-name
                                   (with {:replication {:class "SimpleStrategy"
                                                        :replication_factor 1}})))))

(defn -main
  [cmd & rest]
  (let [session (connect)]
    (cond
      (= cmd "create")  (setup-db session)
      (= cmd "migrate") (migrate session)
      :else             (print "Use either 'migrate' or 'rollback"))))
```

**Comment by mpenet** [comment]
Can you show me your `lein deps :tree` ? 
Try to `lein clean` also. 

I just tried a fresh project with alia 4.0.0-beta10

**Comment by mpenet** [comment]
ok if your project is https://github.com/Codamic/psychopomps/blob/master/project.clj  this might be caused by the dependency on cassaforte which ships with outdated cassandra driver deps, either you need to remove it, or if add exclusions.

**Comment by lxsameer** [comment]
yeah, that's it. Thanks I'll test it and report back
