### ISSUE TITLE
Adjustments to facilitate troywest/arche

### ISSUE THREAD

**Issue by d-t-w** [mpenet/alia#83]
Hi Max,

 I'd like to suggest a couple of changes so I can integrate https://github.com/troy-west/arche a little more cleanly (I like the proxy-session but don't like the way it's currently sort of proxied itself)

 I'll chuck a patch set over over and stick some notes on this ticket.

**Comment by d-t-w** [comment]
Hey Max, I finally got around to reviewing and updating arche. I dropped the proxy-session stuff and currently just shadow Alia execution. I could integrate that more tightly with Alia but it would require a protocol or two.

Main advantage is component/integrant DI/lifecycle and the HugsCQL externalisation / auto -_ translation. I've got a little more cleaning up to do then I'll push a 0.2.0 release. Once that's done I will have a play with protocols and see if it makes sense to integrate it a little more directly.

**Comment by mpenet** [comment]
Hi! 
I somehow didn't see notifications about this issue,(I was on holidays the past 3 weeks). Did you have anything specific in mind? 

Arche looks great btw, congrats. I gladly integrate some ideas of it in alia modules (ex hugsql integration).

**Comment by d-t-w** [comment]
Hey Max, hope the holiday was nice!

I'd love to avoid the fn/module shadowing in Arche like:

https://github.com/troy-west/arche/blob/master/arche-async/src/troy_west/arche/async.clj
https://github.com/troy-west/arche/blob/master/arche-manifold/src/troy_west/arche/manifold.clj

James had an initial crack at using a session-proxy that also carried the statement/encoder state, but it was a bit clunky. Would need a bit of thinking around protocols, probably some change to PStatement, maybe I have a crack at working something through and raise a pull request? Starting place for a discussion at least.

**Comment by mpenet** [comment]
encoder state could be managed via a custom codec maybe? (see the udt aware codec in alia proper).

I guess for pstatement something similar could be done (making that part reify'able the same way it now works with codec), so they could be impl as records/type etc and potentially carry state.

The rest (shadowing) could be solved with protocols certainly.
