### ISSUE TITLE
Overriding pooling options

### ISSUE THREAD

**Issue by moshohayeb** [mpenet/alia#86]
Currently only the following are configurable via the pooling-options
- setCoreConnectionsPerHost
- setMaxConnectionsPerHost
- setNewConnectionThreshold

Is there a way I can override other pooling options defined [here](http://docs.datastax.com/en/drivers/java/2.2/com/datastax/driver/core/PoolingOptions.html). Specifically setMaxRequestsPerConnection?

Thanks

**Comment by mpenet** [comment]
cluster options is set via a multimethod in cluster_options.clj you can extend/overwrite it at runtime.
I d gladly take a PR for this tho, feel free to file one, otherwise I ll just add this option on monday.

**Comment by moshohayeb** [comment]
Super thanks!

Just out of curiosity how do you build the project via lein? I am fairly new to Clojure and having trouble actually testing/using the library after applying said changes to the source files.

**Comment by mpenet** [comment]
I had an awful script to do so. I just made this easier. I can just fire a repl from whatever module (or top level) now. I will move all this to boot at some point.
