### ISSUE TITLE
Integrate arche modules

### ISSUE THREAD

**Issue by d-t-w** [mpenet/alia#99]
Hi Max, 

 Would you be interested in accepting some of the Arche modules into Alia? We still work often with Cassandra but possibly not enough to generate much movement in our own project.

 We use the Integrant and HugCQL modules in production for multiple clients, HugCQL in particular is really useful for externalising prepared statements as resources rather than code.

 I'd need to brush up bits and pieces to get it in order for Alia, happy to put something up for review.

 see: https://github.com/troy-west/arche

**Comment by mpenet** [comment]
Somehow I missed that issue! Sorry about that. 
Sure feel free to send a PR, I like integrant a lot and I could actually see myself using hugsql as well.

**Comment by d-t-w** [comment]
Great, let me catch up with where Alia is now and then I'll start a feature branch / raise a PR.

Might take me a few weeks I've got quite a backlog right now!

**Comment by mpenet** [comment]
Sure no need hurry. I also need to dedicate some time to upgrading to driver 4.x
